自动显存清理和文档更新
svc-develop-team/so-vits-svc pull request #351
Opened 2023-07-29 08:33 UTC by HoshikawaYoru

## 概述
我在使用4.0的时候发现数据集太多会导致生成f0时爆显存，并且貌似没有任何解决办法，当我使用4.1时，发现这个问题被解决了，于是我将原先自己修复4.0的代码移植到4.1中，发现可以正常工作，并且对结果没有太大影响

## 更改
- 我让`preprocess_hubert_f0.py`接受一个新的`--automatic_cache_clearing`参数，用于开启自动显存清理（默认不启用）
- 在日志添加了相关代码
- 在79行，我让cuda主动释放了缓存
- 文档更改

经过测试，我认为这个方案对GPU的占用减小是可行的，并且生成的结果也可以正常用于训练和推理，对结果没有什么影响

2023-07-29 13:51 UTC, Stardust-minus requested changes

2023-07-29 13:51 UTC, Stardust-minus commented on preprocess_hubert_f0.py
> +            torch.cuda.empty_cache()
似乎核心代码是这一行，其实可以直接默认打开，不用传入参数

2023-07-29 14:01 UTC, ms903x1 commented
请问你的显卡型号是什么？显存有多大？

2023-07-29 15:41 UTC, HoshikawaYoru commented
> 请问你的显卡型号是什么？显存有多大？

3060Ti 12G显存

2023-07-29 15:42 UTC, HoshikawaYoru commented on preprocess_hubert_f0.py
> +            torch.cuda.empty_cache()
但是我不确定会不会影响结果，所以我选择让用户手动开启

2023-07-29 16:03 UTC, HoshikawaYoru commented on preprocess_hubert_f0.py
> +            torch.cuda.empty_cache()
> 似乎核心代码是这一行，其实可以直接默认打开，不用传入参数

好的

2023-07-31 03:50 UTC, magic-akari commented
目前 PR 的更改处于无法接受的状态。

1. 描述中出现矛盾，无法确认问题是否真的存在。svc team 中也没有人复现问题。建议先开 issue 描述复现问题的条件和步骤，确认问题真是存在。
2. 根据描述，这是一个 bugfix 而非 feature。那么它不应该是可选开启的。如果仅仅是因为“不确定会不会影响结果”所以引入一个配置项，这是不可接受的。

2023-07-31 04:33 UTC, HoshikawaYoru commented
> 目前 PR 的更改处于无法接受的状态。
> 
> 1. 描述中出现矛盾，无法确认问题是否真的存在。svc team 中也没有人复现问题。建议先开 issue 描述复现问题的条件和步骤，确认问题真实存在可复现。
> 2. 根据描述，这是一个 bugfix 而非 feature。那么它不应该是用户可选开启的。如果仅仅是因为“不确定会不会影响结果”所以引入一个配置项，这是不可接受的。

@magic-akari 我的描述可能有问题，这是一个feature，开启可以让显存占用降低（大部分情况下是这样的），根据我的测试，它可以正常工作，并不会影响结果，并且有着实质性的效果。
而对于我之前提出的问题，我提了一个[Issue](https://github.com/svc-develop-team/so-vits-svc/issues/356)

2023-07-31 05:31 UTC, magic-akari commented
根据文档所述，此处 empty_cache() 属于 API 误用。

>Releases all unoccupied cached memory currently held by the caching allocator so that those can be used in other GPU application and visible in nvidia-smi.
>
>> NOTE
>>
>> empty_cache() doesn’t increase the amount of GPU memory available for PyTorch. However, it may help reduce fragmentation of GPU memory in certain cases. See Memory management for more details about GPU memory management.

https://pytorch.org/docs/stable/notes/cuda.html#cuda-memory-management

> PyTorch uses a caching memory allocator to speed up memory allocations. This allows fast memory deallocation without device synchronizations. However, the unused memory managed by the allocator will still show as if used in nvidia-smi. You can use memory_allocated() and max_memory_allocated() to monitor memory occupied by tensors, and use memory_reserved() and max_memory_reserved() to monitor the total amount of memory managed by the caching allocator. Calling empty_cache() releases all unused cached memory from PyTorch so that those can be used by other GPU applications. However, the occupied GPU memory by tensors will not be freed so it can not increase the amount of GPU memory available for PyTorch.

> For more advanced users, we offer more comprehensive memory benchmarking via memory_stats(). We also offer the capability to capture a complete snapshot of the memory allocator state via memory_snapshot(), which can help you understand the underlying allocation patterns produced by your code.

https://pytorch.org/docs/stable/notes/cuda.html#memory-management


注意：Calling empty_cache() releases all unused cached memory from PyTorch so that those can be used by other GPU applications.
调用 empty_cache 会讲 memory 占用还给系统，供其他 GPU 应用使用。你所描述的情况“memory不足”和此情况相反。

empty_cache 的合理使用情况是：

1. 程序长期运行，需要提前把 memory 还给系统，而不是等到程序执行结束后被系统回收。
2. 程序在后续较长的时间段内不再需要 memory。注意 PyTorch uses a caching memory allocator to speed up memory allocations. 所以对于程序内的 pytorch 占用和分配，pytorch 会自己管理而无需人工干预。

2023-07-31 05:36 UTC, HoshikawaYoru commented
我是想同时训练模型的同时处理下一个数据集的，然后我发现这样做比较有效果，所以我让新增了一个参数来用于这个情况
________________________________
From: magic-akari ***@***.***>
Sent: Monday, July 31, 2023 1:31 PM
To: svc-develop-team/so-vits-svc ***@***.***>
Cc: 星川よる ***@***.***>; Author ***@***.***>
Subject: Re: [svc-develop-team/so-vits-svc] 自动显存清理和文档更新 (PR #351)


根据文档所述，此处 empty_cache() 属于 API 误用。

Releases all unoccupied cached memory currently held by the caching allocator so that those can be used in other GPU application and visible in nvidia-smi.

NOTE

empty_cache() doesn’t increase the amount of GPU memory available for PyTorch. However, it may help reduce fragmentation of GPU memory in certain cases. See Memory management for more details about GPU memory management.

https://pytorch.org/docs/stable/notes/cuda.html#cuda-memory-management

PyTorch uses a caching memory allocator to speed up memory allocations. This allows fast memory deallocation without device synchronizations. However, the unused memory managed by the allocator will still show as if used in nvidia-smi. You can use memory_allocated() and max_memory_allocated() to monitor memory occupied by tensors, and use memory_reserved() and max_memory_reserved() to monitor the total amount of memory managed by the caching allocator. Calling empty_cache() releases all unused cached memory from PyTorch so that those can be used by other GPU applications. However, the occupied GPU memory by tensors will not be freed so it can not increase the amount of GPU memory available for PyTorch.

For more advanced users, we offer more comprehensive memory benchmarking via memory_stats(). We also offer the capability to capture a complete snapshot of the memory allocator state via memory_snapshot(), which can help you understand the underlying allocation patterns produced by your code.

https://pytorch.org/docs/stable/notes/cuda.html#memory-management

注意：Calling empty_cache() releases all unused cached memory from PyTorch so that those can be used by other GPU applications.
调用 empty_cache 会讲 memory 占用还给系统，供其他 GPU 应用使用。你所描述的情况“memory不足”和此情况相反。

empty_cache 的合理使用情况是：

  1.  程序长期运行，需要提前把 memory 还给系统，而不是等到程序执行结束后被系统回收。
  2.  程序在后续较长的时间段内不再需要 memory。注意 PyTorch uses a caching memory allocator to speed up memory allocations. 所以对于程序内的 pytorch 占用和分配，pytorch 会自己管理而无需人工干预。

―
Reply to this email directly, view it on GitHub<https://github.com/svc-develop-team/so-vits-svc/pull/351#issuecomment-1657647736>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A7ZRWVFTZLVLHXSOU4LTSQDXS47KLANCNFSM6AAAAAA24LTMCU>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-07-31 05:38 UTC, HoshikawaYoru commented
这样做应该会提高内存的利用率

2023-07-31 05:45 UTC, ms903x1 commented
不推荐这样的工作流，稳定性太差，而且考虑到大多数使用者的显卡显存都在6g-8g的水平，也不允许在训练的同时预处理。

2023-07-31 05:51 UTC, HoshikawaYoru commented
明白了，但我认为这样做可以满足一部分人的特殊需求，我再更改以下代码和文档，你看这样行吗？
________________________________
From: ms903x1 ***@***.***>
Sent: Monday, July 31, 2023 1:45 PM
To: svc-develop-team/so-vits-svc ***@***.***>
Cc: 星川よる ***@***.***>; Author ***@***.***>
Subject: Re: [svc-develop-team/so-vits-svc] 自动显存清理和文档更新 (PR #351)


不推荐这样的工作流，稳定性太差，而且考虑到大多数使用者的显卡显存都在6g-8g的水平，也不允许在训练的同时预处理。

―
Reply to this email directly, view it on GitHub<https://github.com/svc-develop-team/so-vits-svc/pull/351#issuecomment-1657671892>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A7ZRWVELDKKFZKCEPUBYW23XS5A7BANCNFSM6AAAAAA24LTMCU>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-07-31 05:53 UTC, ms903x1 commented
我投弃权票，还是要看其他三位的意见.

2023-08-03 04:02 UTC, closed without merging